name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
assignees: ["o-lukas"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Before opening the issue, have you...?
      description: This is to minimize the amount of duplicate issues.
      options:
        - label: Searched for existing issues
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    validations:
      required: true
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    validations:
      required: true
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
